# Generated by Django 5.2 on 2025-05-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='Barbeiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_como_barbeiro', to='schedulle.cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_como_cliente', to='schedulle.cliente'),
        ),
    ]
