# Generated by Django 5.2 on 2025-05-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedulle', '0003_barbeiro_alter_agendamento_barbeiro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendamento',
            old_name='Barbeiro',
            new_name='barbeiro',
        ),
    ]
